language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script: 
  - asdf plugin-add https://github.com/pirackr/asdf-telepresence ./
  - asdf list-all telepresence
  - asdf plugin-test telepresence ./ --asdf-plugin-gitref $TRAVIS_COMMIT 'telepresence version'
os:
  - linux
  - osx
arch:
  - amd64
  - arm64
  - ppc64le
