# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-linux:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: install asdf
          command: |
            [ -d ~/.asdf-vm ] || git clone https://github.com/asdf-vm/asdf.git ~/.asdf-vm
            echo 'source ~/.asdf-vm/asdf.sh' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: install asdf-telepresence
          command: asdf plugin-add telepresence .

      - run:
          name: list-all telepresence
          command: asdf list-all telepresence

      - run:
          name: run plugin test
          command: asdf plugin test telepresence ./ --asdf-plugin-gitref $CIRCLE_BRANCH telepresence version

workflows:
  build:
    jobs:
      - build-linux
